<?php

/**
 * @file
 * Provide CiviCRM entity views extras, Views relationships and other handlers for entities exposed by CiviCRM Entity
 */

function civicrm_entity_views_extras_views_api() {
  return array(
    'api' => 3,
  );
}

function civicrm_entity_views_extras_views_data() {
  $data['civicrm_price_set_entity']['table']['group'] = t('CiviCRM Price Set Entities');

  $data['civicrm_price_set_entity']['table']['base'] = array(
    'field' => 'id',
    'title' => t('CiviCRM Price Set Entities'),
    'help' => t("View displays CiviCRM Price Set to Entity mapping info"),
  );


  //----------------------------------------------------------------
  // CIVICRM Price Set Entity - FIELDS
  //----------------------------------------------------------------

  // Numeric: Price Set ID
  $data['civicrm_price_set_entity']['price_set_id'] = array(
    'title' => t('Price Set ID'),
    'help' => t('The numeric ID of the Price Set'),
    'field' => array(
      'handler' => 'views_handler_field_numeric',
      'click sortable' => TRUE,
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_numeric',
      'numeric' => TRUE,
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_numeric',
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
  );

  // Entity Table
  $data['civicrm_price_set_entity']['entity_table'] = array(
    'title' => t('Entity Table'),
    'help' => t('The entity table for the Price Set'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
      'allow empty' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
  );

  //----------------------------------------------------------------
  // CIVICRM Price Set Entity - TABLE JOINS
  //----------------------------------------------------------------

  $data['civicrm_price_set_entity']['table']['join'] = array(
    // Directly links to event table.
    'civicrm_event' => array(
      'left_field' => 'id',
      'field' => 'entity_id',
    ),
  );

  $data['civicrm_event']['table']['join']['civicrm_price_set_entity'] = array(

    'left_field' => 'entity_id',
    'field' => 'id',

  );

  //----------------------------------------------------------------
  // CIVICRM Price Set Entity - RELATIONSHIPS
  //----------------------------------------------------------------

  // Price Set
  $data['civicrm_price_set_entity']['civicrm_price_set'] = array(
    'title' => t('Price Set'),
    'help' => t('Price Set for this Entity'),
    'real field' => 'price_set_id',
    'relationship' => array(
      'base' => 'civicrm_price_set',
      'base field' => 'id',
      'handler' => 'views_handler_relationship',
      'label' => t('Price Set'),
    ),
  );

  $data['civicrm_price_set']['civicrm_price_field'] = array(
    'group' => t('Price Field'),
    'title' => t('CiviCRM Price field'),
    'help' => t('Joins with the civicrm_price_field table'),
    'relationship' => array(
      'handler' => 'views_handler_relationship',
      'label' => t('Price Field'),
      'title' => t('Price Field'),
      'base' => 'civicrm_price_field',
      'base field' => 'price_set_id',
      'relationship field' => 'id',
    ),
  );

  // Price Field Value
  $data['civicrm_price_field']['civicrm_price_field_value'] = array(
    'title' => t('Price Field Value'),
    'help' => t('Value(s) for this Price Field'),
    'real field' => 'id',
    'relationship' => array(
      'base' => 'civicrm_price_field_value',
      'base field' => 'price_field_id',
      'handler' => 'views_handler_relationship',
      'label' => t('Price Field Value'),
    ),
  );


  //----------------------------------------------------------------
  // CIVICRM Membership Payment - RELATIONSHIPS
  //----------------------------------------------------------------

  // Membership
  $data['civicrm_membership_payment']['civicrm_membership'] = array(
    'title' => t('CiviCRM Member'),
    'help' => t('Relates Membership to Membership Payment'),
    'real field' => 'membership_id',
    'relationship' => array(
      'base' => 'civicrm_membership',
      'base field' => 'id',
      'handler' => 'views_handler_relationship',
      'label' => t('CiviCRM Memberships'),
    ),
  );
  // Contribution
  $data['civicrm_membership_payment']['civicrm_contribution'] = array(
    'title' => t('CiviCRM Contributions'),
    'help' => t('Relates Contribution to Membership Payment'),
    'real field' => 'contribution_id',
    'relationship' => array(
      'base' => 'civicrm_contribution',
      'base field' => 'id',
      'handler' => 'views_handler_relationship',
      'label' => t('CiviCRM Contributions'),
    ),
  );
  return $data;
}