<?php

/**
 * @file
 * Implement CiviCRM entities as a Drupal Entity.
 */

/**
 * Implements hook_menu_later().
 *
 * Entity API creates all the fields page links but the basic 'manage' page is missing
 * so we use the /fields page at that url
 */
function civicrm_entity_menu_alter(&$items) {
  foreach (entity_get_info() as $entity_name => $entity_info) {
    if (!empty($entity_info['module']) &&
      $entity_info['module'] == 'civicrm_entity'
    ) {
      foreach ($entity_info['bundles'] as $file_type => $bundle_info) {
        if (isset($bundle_info['admin'])) {
          // Get the base path and access.
          $path = $bundle_info['admin']['path'];
          $items[$path] = $items[$path . '/fields'];
          $items[$path]['type'] = MENU_NORMAL_ITEM;
          $items[$path]['title'] = $entity_info['label'];
          $items[$path]['description'] = t('CiviCRM @entity entity', array('@entity' => $entity_name));
          $items[$path . '/fields']['type'] = MENU_DEFAULT_LOCAL_TASK;
        }
      }
    }
  }
}

/**
 * Implements hook_permission().
 */
function civicrm_entity_permission() {
  return array(
    'civicrm_entity.rules.administer' => array(
      'title' => t('Administer CiviCRM rule configurations'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Entity access callback.
 *
 * @param $op
 * @param $entity
 * @param $account
 * @param $entity_type
 *
 * @return bool
 */
function civicrm_entity_access($op, $entity, $account, $entity_type) {
  if ($op == 'view' && $entity_type == 'civicrm_event') {
    return user_access('view event info');
  }
  elseif ($op == 'view' && $entity_type == 'civicrm_participant') {
    return user_access('view event participants');
  }
  else {
    return user_access('administer CiviCRM');
  }
}

/**
 * Implements hook_views_data_alter().
 */
/*
function civicrm_entity_views_data_alter($data) { }
*/

/**
 * Implements hook_schema_alter().
 *
 * Note we are just doing this in a very simple form relationship type
 * which is not defined by views at this stage. We have the problem
 * that the CiviCRM views integration uses the _data hook & would need
 * to use _data_alter hook to be compatible with entity views
 * integration
 *
 * @param $schema
 */
function civicrm_entity_schema_alter(&$schema) {
  $schema_entities = _civicrm_entity_enabled_entities();;
  foreach ($schema_entities as $drupal_entity => $civicrm_entity) {
    $schema[$drupal_entity] = civicrm_entity_get_schema($drupal_entity);
  }
}

/**
 * Get schema for entities.
 *
 * This approach may not be required as using the schema_alter hook
 * (as opposed to schema_hook) seems to get around a bunch of the
 * reasons I used a separate schema.
 *
 * @param $table
 *
 * @return array
 */
function civicrm_entity_get_schema($table) {
  if (!civicrm_initialize(TRUE)) {
    return;
  }
  $schema = array();
  $schema[$table] = array(
    'description' => 'The base table for ' . $table,
    'primary key' => array('id'),
    'fields' => array(),
  );
  $civicrm_entity = substr($table, 8);

  $fields = civicrm_api($civicrm_entity, 'getfields', array('version' => 3));
  $fields = $fields['values'];
  foreach ($fields as $fieldname => $field_spec) {
    if (empty($field_spec['name'])) {
      continue;
    }
    $unique_name = empty($field_spec['uniqueName']) ? $fieldname : $field_spec['uniqueName'];
    $schema[$table]['fields'][$unique_name] = array(
        'real_field' => $field_spec['name'],
        'description' => _civicrm_entity_get_title($field_spec),
        'unsigned' => TRUE,
        'not null' => TRUE,
      ) + civicrm_entity_get_field_type($field_spec);
  }
  return empty($schema[$table]) ? array() : $schema[$table];

}

/**
 * Please document this function.
 *
 * @param $field_spec
 *
 * @return array
 */
function civicrm_entity_get_field_type($field_spec) {
  if ($field_spec['name'] == 'id') {
    return array('type' => 'serial');
  }
  if (!isset($field_spec['type'])) {
    return array('type' => 'text', 'field_type' => 'text');
  }

  switch ($field_spec['type']) {
    case CRM_Utils_Type::T_INT:
    case CRM_Utils_Type::T_BOOLEAN:
      return array('type' => 'integer', 'field_type' => 'number_integer');

    case CRM_Utils_Type::T_MONEY:
    case CRM_Utils_Type::T_FLOAT:
      return array('type' => 'float');

    case CRM_Utils_Type::T_TEXT:
    case CRM_Utils_Type::T_STRING:
    case CRM_Utils_Type::T_LONGTEXT:
    case CRM_Utils_Type::T_CCNUM:
    case CRM_Utils_Type::T_EMAIL:
    case CRM_Utils_Type::T_URL:
      return array('type' => 'text','field_type' => 'text');

    case CRM_Utils_Type::T_DATE:
    case CRM_Utils_Type::T_TIME:
    case (CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME):
      return array('type' => 'varchar', 'mysql_type' => 'datetime');

    case CRM_Utils_Type::T_ENUM:
      return array('type' => 'varchar', 'mysql_type' => 'enum');

    case CRM_Utils_Type::T_BLOB:
    case CRM_Utils_Type::T_MEDIUMBLOB:
      return array('type' => 'blob');

    case CRM_Utils_Type::T_TIMESTAMP:
      return array('type' => 'varchar', 'mysql_type' => 'timestamp');

  }
  return array('type' => $field_spec['type']);
}

/**
 * Here we declare selected CiviCRM entities to Drupal.
 *
 * This is necessary for entity module to pick them up.
 */
function civicrm_entity_entity_info() {
  $entities = _civicrm_entity_enabled_entities();

  foreach ($entities as $drupal_entity => $civicrm_entity) {
    $info[$drupal_entity] = array(
      'description' => $civicrm_entity,
      'optional' => TRUE,
      'label' => "CiviCRM " . ucwords($civicrm_entity),
      'module' => 'civicrm_entity',
      'controller class' => 'CivicrmEntityController',
      'metadata controller class' => 'CivicrmEntityMetadataController',
      'views controller class' => 'CiviCRMEntityDefaultViewsController',
      'ui class' => 'RulesDataUIEntity',
      'fieldable' => TRUE,
      'extra fields controller class' => 'EntityDefaultExtraFieldsController',
      'access callback' => 'civicrm_entity_access',
      'admin ui' => array(
        'path' => $drupal_entity,
        'controller class' => 'CivicrmEntityUIController',
        'file' => 'civicrm_entity_controller.inc',
      ),
      'bundles' => array(
        $drupal_entity => array(
          'label' => t('CiviCRM @entity', array('@entity' => ucwords($civicrm_entity))),
          'admin' => array(
            'path' => 'admin/structure/types/manage/' . $drupal_entity,
            'access arguments' => array('administer CiviCRM'),
          ),
        ),
      ),
      'view modes' => array(
        'full' => array(
          'label' => t('Default'),
          'custom settings' => TRUE,
        ),
      ),
      'entity keys' => array(
        'id' => 'id',
        'label' => _civicrm_entity_labels($drupal_entity),
      ),
      'base table' => $drupal_entity,
    );
    $label_callback = 'civicrm_entity_' . $drupal_entity . '_label_callback';
    if (function_exists($label_callback)) {
      $info[$drupal_entity]['label callback'] = $label_callback;
    }
  }
  return $info;
}

/**
 * Here we declare Selected CiviCRM entities fields to Drupal.
 *
 * Some trickiness here as declaring the 'schema' via our special civi
 * schema function seems to cause fields to be declared twice if we us
 * property_info rather than property_info_alter.
 *
 * At the moment civicrm_relationship_type is the only entity being
 * managed through 'our' schema.
 *
 * @param $info
 *
 * @return
 */
function civicrm_entity_entity_property_info_alter(&$info) {
  if (!civicrm_initialize(TRUE)) {
    return;
  }

  // We'll start with a few basic entities but we could get them the
  // same way the API explorer does.
  $entities = _civicrm_entity_enabled_entities();
  foreach ($entities as $drupal_entity => $civicrm_entity) {
    $info[$drupal_entity]['properties'] = _civicrm_entity_getproperties($civicrm_entity, 'property_info');
    // $info[$drupal_entity]['bundles'] = array();
  }
  // This makes the drupal user available when chaining from a rule.
  $info['civicrm_contact']['properties']['civicrm_user'] = array(
    'label' => 'Drupal User',
    'description' => 'Drupal User for contact',
    'type' => 'user',
  );

  // Attach a CiviCRM Contact property to drupal users.
  $info['user']['properties']['civicrm_contact'] = array(
    'label' => 'CiviCRM Contact',
    'description' => 'CiviCRM Contact for user',
    'type' => 'civicrm_contact',
    'field' => FALSE,
    'translatable' => FALSE,
    'getter callback' => 'civicrm_entity_user_contact_get',
  );

  return $info;
}


/**
 * Whitelist of enabled entities. We don't have a compelling reason for not including all entities
 * but some entities are fairly non-standard and of course the rule hook would instantiate rules
 * more often if all were enabled.
 *
 * The whitelist approach is mostly out of caution
 *
 * @return array of enabled entities keyed by the drupal entity name
 */
function _civicrm_entity_enabled_entities() {
  $whitelist = array(
    'civicrm_activity' => 'activity',
    'civicrm_action_schedule' => 'action_schedule',
    'civicrm_address' => 'address',
    'civicrm_contact' => 'contact',
    'civicrm_contribution' => 'contribution',
    'civicrm_email' => 'email',
    'civicrm_entity_tag' => 'entity_tag',
    'civicrm_event' => 'event',
    'civicrm_group' => 'group',
    'civicrm_grant' => 'grant',
    'civicrm_membership' => 'membership',
    'civicrm_membership_type' => 'membership_type',
    'civicrm_participant' => 'participant',
    'civicrm_phone' => 'phone',
    'civicrm_price_set' => 'price_set',
    'civicrm_price_field' => 'price_field',
    'civicrm_price_field_value' => 'price_field_value',
    'civicrm_relationship' => 'relationship',
    'civicrm_relationship_type' => 'relationship_type',
    'civicrm_tag' => 'tag',
  );
  //dirty check for whether financialType exists
  if (!method_exists('CRM_Contribute_PseudoConstant', 'contributionType')) {
    $whitelist['civicrm_financial_type'] = 'financial_type';
  }
  _civicrm_enabled_entity_alter_whitelist($whitelist);
  return $whitelist;
}

/**
 * Allow extensions to alter entities
 * @param array $whitelist
 *
 * @return mixed
 */
function _civicrm_enabled_entity_alter_whitelist(&$whitelist) {
  if (!civicrm_initialize()) {
    return;
  }
  $codeVersion = explode('.', CRM_Utils_System::version());
  // if db.ver < code.ver, time to upgrade
  if (version_compare($codeVersion[0] . '.' . $codeVersion[1], 4.5) >= 0) {
    return CRM_Utils_Hook::singleton()->invoke(1, $whitelist,
      CRM_Core_DAO::$_nullObject, CRM_Core_DAO::$_nullObject, CRM_Core_DAO::$_nullObject, CRM_Core_DAO::$_nullObject,
      CRM_Core_DAO::$_nullObject,
      'civicrm_alter_drupal_entities'
    );
  }
  else {
    return CRM_Utils_Hook::singleton()->invoke(1, $whitelist,
      CRM_Core_DAO::$_nullObject, CRM_Core_DAO::$_nullObject, CRM_Core_DAO::$_nullObject, CRM_Core_DAO::$_nullObject,
      'civicrm_alter_drupal_entities'
    );
  }
}

/**
 * @param array $labels
 *
 * @return mixed
 */
function _civicrm_enabled_entity_alter_labels(&$labels) {
  if (!civicrm_initialize()) {
    return;
  }
  $codeVersion = explode('.', CRM_Utils_System::version());
  // if db.ver < code.ver, time to upgrade
  if (version_compare($codeVersion[0] . '.' . $codeVersion[1], 4.5) >= 0) {
    return CRM_Utils_Hook::singleton()->invoke(1, $labels,
      CRM_Core_DAO::$_nullObject, CRM_Core_DAO::$_nullObject, CRM_Core_DAO::$_nullObject, CRM_Core_DAO::$_nullObject,
      CRM_Core_DAO::$_nullObject,
      'civicrm_alter_drupal_entity_labels'
    );
  }
  else {
    return CRM_Utils_Hook::singleton()->invoke(1, $labels,
      CRM_Core_DAO::$_nullObject, CRM_Core_DAO::$_nullObject, CRM_Core_DAO::$_nullObject, CRM_Core_DAO::$_nullObject,
      'civicrm_alter_drupal_entity_labels'
    );
  }
}

/**
 * Please document this function.
 */
function _civicrm_entity_chained_fks() {
  return array(
    'CRM_Contact_DAO_Contact' => 'contact',
    'CRM_Event_DAO_Event' => 'event',
  );
}

/**
 * Provide label (column) for each entity types - default to id if nothing specified.
 *
 * @TODO Use the CiviCRM 4.5 getlist function - possibly ported into this module to support 4.4
 *
 * @see http://api.drupal.org/api/drupal/modules!system!system.api.php/function/hook_entity_info/7
 *
 * @param $entity
 * @return string
 */
function _civicrm_entity_labels($entity) {
  $labels = array(
    'civicrm_activity' => 'subject',
    'civicrm_action_schedule' => 'name',
    'civicrm_address' => 'address_name',
    'civicrm_contact' => 'display_name',
    'civicrm_contribution' => 'contribution_source',
    'civicrm_email' => 'email',
    'civicrm_event' => 'title',
    'civicrm_entity_tag' => 'tag_id',
    'civicrm_financial_type' => 'description',
    'civicrm_group' => 'name',
    'civicrm_membership_type' => 'name',
    'civicrm_participant' => 'source',
    'civicrm_phone' => 'phone',
    'civicrm_relationship' => 'description',
    'civicrm_relationship_type' => 'description',
    'civicrm_tag' => 'name',
  );
  _civicrm_enabled_entity_alter_labels($labels);
  return isset($labels[$entity]) ? $labels[$entity] : 'id';
}

function _civicrm_entity_get_title($field_specs, $entity_type = '') {
  if (!empty($entity_type)) {
    $label_field = _civicrm_entity_labels($entity_type);
  }
  else {
    $label_field = 'title';
  }
  if (empty($field_specs[$label_field])) {
    if (array_key_exists('label', $field_specs)) {
      $label_field = 'label';
    }
    else if (array_key_exists('name', $field_specs)) {
      $label_field = 'name';
    }
  }

  $label = $field_specs[$label_field];

  if (!empty($field_specs['groupTitle'])) {
    $label = $field_specs['groupTitle'] . ': ' . $label;
  }

  return empty($label) ? 'Title not defined in schema' : $label;
}

/**
 * Label callback for civicrm_contact entity type.
 *
 *   drupal_alter('civicrm_entity_' . $entity, $, $alterable2, $context);
 *
 * @param $entity
 * @param $entity_type
 *
 * @return null|string
 */
function civicrm_entity_civicrm_contact_label_callback($entity, $entity_type) {
  $label = isset($entity->display_name) ? $entity->display_name : '';
  // drupal_alter('civicrm_entity_contact_label', $label, $entity);
  if (isset($entity->email) && !empty($entity->email)) {
    $label = t('!label <!email>', array(
        '!label' => $label,
        '!email' => $entity->email
      ));
  }
  elseif (isset($entity->phone) && !empty($entity->phone)) {
    $label = t('!label <!phone>', array(
        '!label' => $label,
        '!phone' => $entity->phone
      ));
  }
  return $label;
}
/**
 * Please document this function.
 *
 * @param $field_spec
 *
 * @return array
 */
function civicrm_entity_get_field_widget($field_spec,$civicrm_entity) {
  $widget = array();

  if (isset($field_spec['name']) && $field_spec['name'] == 'id') {
    $widget =  array('widget' => 'hidden');
  }

  if(!isset($field_spec['type'])) {
    $widget = array('widget' => 'hidden');
  }

  if(isset($field_spec['html']['type'])) {
   switch ($field_spec['html']['type']) {
    case 'Text':
      $widget = array('widget' => 'textfield');
      break;
    case 'Select':
      $widget = array('widget' => 'select');
      $widget['options'] = civicrm_entity_get_field_options($field_spec['name'], $civicrm_entity);
      break;
    case 'Autocomplete-Select':
      $widget = array('widget' => 'textfield');
      break;
    case 'CheckBox':
      $widget = array('widget' => 'checkbox');
      break;
    case 'RichTextEditor':
    case 'TextArea':
      $widget = array('widget' => 'textarea');
      break;

    default: break;
   }
  }
  else {
    $widget = array('widget' =>'textfield');
  }

  if(isset($field_spec['type'])) {

     switch($field_spec['type']) {
       case 4:
         $widget = array('widget' => 'date_select','format' => 'Y:m:d');
         break;
       case 8:
         $widget = array('widget' => 'date_select','format' => 'H:i:s');
         break;
       case 12:
         $widget = array('widget' => 'date_select','format' => 'Y:m:d H:i:s');
         break;
     }
  }

  return $widget;
}

function civicrm_entity_get_field_options($field_name, $civicrm_entity){
  $result = civicrm_api($civicrm_entity, 'getoptions', array('sequential'=>1,'version' => 3, 'field' => $field_name));
  $options = array(NULL => '- No Value -');
  if(!$result['is_error']) {
    foreach($result['values'] as $option) {
      $options[$option['key']] = $option['value'];
    }
    return $options;
  }
  else return array();
}
/**
 * Calculate fields for entities
 *
 * @param $civicrm_entity
 * @param string $context
 *
 * @return array
 */
function _civicrm_entity_getproperties($civicrm_entity, $context = '') {
  $info = array();
  if ($civicrm_entity == 'contact') {
    $info['civi_user'] = array(
      'label' => 'Drupal User',
      'type' => 'user',
    );
  }
  $fields = civicrm_api($civicrm_entity, 'getfields', array(
    'version' => 3,
    'action' => 'create',
  ));
  foreach ($fields['values'] as $fieldname => $field_specs) {
    // Type is empty for custom fields - we should sort that out but
    // skipping for now we are only doing 'integers' at this stage.
    $types = array(
      1 => 'integer',
      2 => 'text',
      32 => 'text',
      16 => 'integer',
      4 => 'datetime',
      8 => 'datetime',
      12 => 'datetime',
      256 => 'datetime',
      512 => 'decimal',
      1024 => 'decimal',
    );
    if (!empty($field_specs['type']) &&
      array_key_exists($field_specs['type'], $types)
    ) {
      //determine the label of the field
      $label = _civicrm_entity_get_title($field_specs);
      $info[$fieldname] = array(
        'label' => $label,
        'type' => $types[$field_specs['type']],
        'sanitize' => 'check_plain',
        'setter callback' => 'entity_property_verbatim_set',
      );
      if (!empty($field_specs['api.required'])) {
        $info[$fieldname]['required'] = TRUE;
      }
      if ($field_specs['type'] == 16) {
        $info[$fieldname]['size'] = 'tiny';
      }
      if ($types[$field_specs['type']] == 'datetime') {
        unset($info[$fieldname]['type']);
        $info[$fieldname]['mysql_type'] = 'datetime';
        $info[$fieldname]['tz_handling'] = 'site';
        $info[$fieldname]['offset_field'] = '';
        $info[$fieldname]['related_fields'] = array();
        switch ($field_specs['type']) {
          case 4:
            $info[$fieldname]['granularity'] = array('year', 'month', 'day');
            break;
          case 8:
            $info[$fieldname]['granularity'] = array(
              'hour',
              'minute',
              'second'
            );
          case 12:
            $info[$fieldname]['granularity'] = array(
              'year',
              'month',
              'day',
              'hour',
              'minute',
              'second'
            );
        }
      }
      // This is a semi-reliable way of distinguishing 'real' fields
      // from pseudo fields and custom fields and impacts on views
      if (!empty($field_specs['name'])) {
        $info[$fieldname]['schema field'] = $field_specs['name'];
      }

      //widget code
      $info[$fieldname]['widget'] = civicrm_entity_get_field_widget($field_specs,$civicrm_entity);

      // We will add contact as a related entity for FK references to
      // contact. This could be expanded to all FKs e.g event_id in
      // Participant. Could load the event at the moment we are being
      // cautious.
      if (CRM_Utils_Array::value('FKClassName', $field_specs)) {
        $fks = _civicrm_entity_chained_fks();
        if (array_key_exists($field_specs['FKClassName'], $fks)) {
          $fks_entity = $fks[$field_specs['FKClassName']];
          $info[$fieldname . '_' . $fks_entity] = array(
            'label' => _civicrm_entity_get_title($field_specs),
            'type' => 'civicrm_' . $fks_entity,
            'property_info' => array(
              'field' => $fieldname,
              'entity' => $fks_entity,
            ),
            'getter callback' => 'civicrm_entity_metadata_civicrm_entity_get_properties',
          );
        }
      }
      // @TODO We are treating contact as the only possible entity
      // which is not great - need to figure out better approach - can
      // we have more than one? Define 'civicrm_entity'?
      if ($fieldname == 'entity_id') {
        $fks_entity = 'contact';
        $info[$fieldname . '_' . $fks_entity] = array(
          'label' => _civicrm_entity_get_title($field_specs),
          'type' => 'civicrm_' . $fks_entity,
          'property_info' => array(
            'field' => $fieldname,
            'entity' => $fks_entity,
          ),
          'getter callback' => 'civicrm_entity_metadata_civicrm_entity_get_properties',
        );
      }

      if (!empty($field_specs['options'])) {
        // $info[$fieldname]['type'] = 'list<integer>';
        $info[$fieldname]['options list'] = '_civicrm_entity_rules_attach_options';
        $info[$fieldname]['options data'] = $field_specs['options'];
        if ($context == 'property_info') {
          $info[$fieldname]['property defaults']['options list'] = $field_specs['options'];
        }
      }

      $info['type'] = array(
        'label' => t('Type'),
        'description' => t('Dummy field for bundle key'),
        'type' => 'token',
        'setter callback' => 'entity_property_verbatim_set',
        'required' => FALSE,
        'property defaults' => array('civicrm_' . strtolower($civicrm_entity)),
      );
    }
  }
  return $info;
}

function civicrm_entity_form($form, &$form_state, $entity_id, $op, $entity_type) {

  if ($op == 'edit' || $op == 'delete') {
    $entity = entity_load($entity_type, array($entity_id));
    $entity = $entity[$entity_id];
    $form_state['entity'] = $entity;
    $form_state['entity_type'] = $entity_type;
  }
  if ($op == 'create') {
    $entity = new CiviCRMEntity(array(), $entity_type);
    $entity->is_new = TRUE;
    $entity->type = $entity_type;
    $form_state['entity'] = $entity;
    $form_state['entity_type'] = $entity_type;
  }
  // Add the field related form elements.
  if ($op == 'edit' || $op == 'create') {
    if($op == 'edit') {
      $title = 'Edit ' . ucwords(str_replace("_", " ", $entity_type)) . ": " . entity_label($entity_type, $entity) . " (id:" . $entity->id . ")";
    }
    else {
      $title = 'Add ' . ucwords(str_replace("_", " ", $entity_type));
    }

    field_attach_form($entity_type, $entity, $form, $form_state);

    //get entity controller build content
    if ($op == 'edit') {
      $wrapper = entity_metadata_wrapper($entity_type, $entity);
    }
    else {
      $wrapper = entity_metadata_wrapper($entity_type);
    }
    foreach ($wrapper as $name => $child) {
      $info = $child->info();
      if (strpos($info['name'], 'field_') === 0) {
        continue;
      }
      else {
       if(isset($info['widget']['widget'])){
          $form[$name] = array(
            '#type' => $info['widget']['widget'],
            '#title' => $info['label'],
            '#description' => !empty($info['description']) ? $info['description'] : '',
            '#default_value' => $op == 'edit' ? $child->value() : '',
          );
          //set the options for select options
          if($form[$name]['#type'] == 'select') {
            $form[$name]['#options'] = $info['widget']['options'];
          }
          // Date field handling, check for date_api module to use date select widget
          // else fallback to textfield
          if($form[$name]['#type'] == 'date_select') {
            if(module_exists('date_api')){
              $form[$name]['#format'] = $info['widget']['format'];
            }
            else {
              $form[$name]['#type'] = 'textfield';
            }
          }
          //for some reason the is_deleted column of the contact record is coming to the entity
          // as contact_is_deleted ...special handling to have the form value set properly
          if($name == 'is_deleted') {
            if($entity_type=='civicrm_contact') {
              $form[$name]['#default_value'] = $entity->contact_is_deleted;
            }
          }

        } // end if isset widget
      } // end else not a drupal field
    } // end foreach

    $form['actions'] = array(
      '#type' => 'container',
      '#attributes' => array('class' => array('form-actions')),
      '#weight' => 400,
    );

    $form['#validate'] = array();
    $form['#submit'] = array();
    $form['#validate'][] = 'civicrm_entity_form_validate';
    $form['#submit'][] = 'civicrm_entity_form_submit';
    // We add the form's #submit array to this button along with the actual submit
    // handler to preserve any submit handlers added by a form callback_wrapper.
    $submit = array();

    if (!empty($form['#submit'])) {
      $submit += $form['#submit'];
    }

    $form['actions']['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Save'),
      '#submit' => $submit + array(),
    );
  } //end if op is add or edit

  if ($op == 'delete') {

    $form['delete_markup'] = array(
      '#type' => 'markup',
      '#markup' => '<div></strong>' . t('Are you sure you want to delete ') .
        $entity_type . " id: " . $entity->id . '</strong></div>',
    );

    $form['actions'] = array(
      '#type' => 'container',
      '#attributes' => array('class' => array('form-actions')),
      '#weight' => 400,
    );

    $form['#validate'] = array();
    $form['#submit'] = array();
    $form['#validate'][] = 'civicrm_entity_delete_form_validate';
    $form['#submit'][] = 'civicrm_entity_delete_form_submit';
    // We add the form's #submit array to this button along with the actual submit
    // handler to preserve any submit handlers added by a form callback_wrapper.

    $form['actions']['cancel'] = array(
      '#type' => 'submit',
      '#value' => t('Cancel'),
      '#submit' => array('civicrm_entity_delete_form_cancel_submit'),
    );

    $form['actions']['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Delete'),
      '#submit' => $form['#submit'],
    );

    $title = 'Delete ' . ucwords(str_replace("_", " ", $entity_type)) . ": " . entity_label($entity_type, $entity) . " (id:" . $entity->id . ")";;
  }
  $title = str_replace("Civicrm", "CiviCRM", $title);
  drupal_set_title($title);

  return $form;
}

/**
 * Form API validate callback for the entity form
 */
function civicrm_entity_form_validate(&$form, &$form_state) {
  $entity = $form_state['entity'];
  $entity_type = $form_state['entity_type'];
  foreach ($form_state['values'] as $key => $value) {
    $entity->{$key} = $value;
  }
  // Notify field widgets to validate their data.
  field_attach_form_validate($entity_type, $entity, $form, $form_state);

}

/**
 * Form API submit callback for the entity form.
 *
 */
function civicrm_entity_form_submit(&$form, &$form_state) {
  $entity_type = $form_state['entity_type'];
  $entity = $form_state['entity'];
  foreach ($form_state['values'] as $key => $value) {
    $entity->{$key} = $value;
  }

  // Add in created and changed times.
  if ($entity->is_new = isset($entity->is_new) ? $entity->is_new : 0) {
    $entity->created = time();
  }
  $entity->changed = time();

  $wrapper = entity_metadata_wrapper($entity_type, $entity);
  field_attach_submit($entity_type, $entity, $form, $form_state);
  $wrapper->save();

  $t_args = array(
    '%label' => entity_label($entity_type, $entity),
  );
  $form_state['redirect'] = str_replace('_', '-', $entity_type) . '/' . $entity->id;
  drupal_set_message(t('Drupal fields and %label properties have been updated.', $t_args));
  drupal_redirect_form($form_state);
}

/**
 * Form API validate callback for the entity delete form
 */
function civicrm_entity_delete_form_validate(&$form, &$form_state) {

}

/**
 * Form API submit callback for the entity delete form.
 *
 */
function civicrm_entity_delete_form_submit(&$form, &$form_state) {
  $entity_type = $form_state['entity_type'];
  $entity = $form_state['entity'];
  $wrapper = entity_metadata_wrapper($entity_type, $entity);
  $wrapper->delete();
  $form_state['redirect'] = '';
  drupal_redirect_form($form_state);
}

/**
 * Form API submit callback for the entity delete form cancel button.
 *
 */
function civicrm_entity_delete_form_cancel_submit(&$form, &$form_state) {
  $entity_type = $form_state['entity_type'];
  $entity = $form_state['entity'];

  $form_state['redirect'] = str_replace('_', '-', $entity_type) . '/' .
    $entity->id;
  drupal_redirect_form($form_state);
}

/**
 * Implement getter callback.
 *
 * NB this is in a separate file called callbacks.inc in entity module
 * - I couldn't see how it was loaded so maybe the name has some
 * magic?
 *
 * @param $data
 * @param $options
 * @param $name
 * @param $type
 * @param $info
 *
 * @return object
 */
function civicrm_entity_metadata_civicrm_entity_get_properties($data, $options, $name, $type, $info) {
  $entity = civicrm_api($info['property_info']['entity'], 'get', array(
    'version' => 3,
    'id' => $data->$info['property_info']['field'],
    'sequential' => 1,
  ));
  return (object) $entity['values'][0];
}

/**
 * Condition Drupal User Account exists for contact.
 *
 * @param array $contact
 *   Contact array.
 *
 * @return object
 *   Drupal user object if success, FALSE on fail.
 */
function civicrm_entity_user_exists($contact) {
  return civicrm_entity_action_load_user($contact);
}

/**
 * Condition Drupal User Account can be created for contact (creates contact).
 *
 * @param array $contact
 *   contact array
 *
 * @return object
 *   Drupal user object if success, FALSE on Fail
 */
function civicrm_entity_user_creatable($contact) {
  return civicrm_entity_action_create_user($contact, TRUE);
}

/**
 * Condition Drupal User Account can be created or exists for contact.
 *
 * Ccreates contact if appropriate.
 *
 * @param array $contact
 *   contact array
 *
 * @return mixed
 *   Drupal user object if success, FALSE on fail.
 */
function civicrm_entity_user_exists_or_creatable($contact) {
  return civicrm_entity_action_load_create_user($contact);
}

/**
 * Given a contact object return the Drupal user.
 *
 * @param StdClass $entity
 *   Contact Std Object
 *
 * @return object
 *   Drupal user object.
 */
function civicrm_entity_action_load_user($entity) {
  $domain_id = civicrm_api('domain', 'getvalue', array(
    'version' => 3,
    'return' => 'id',
    'current_domain' => TRUE,
  ));
  $params = array(
    'version' => 3,
    'contact_id' => $entity->id,
    'return' => 'uf_id',
    'domain_id' => $domain_id,
  );
  $contact = civicrm_api('uf_match', 'getsingle', $params);
  if (empty($contact['is_error'])) {
    return array('civicrm_user' => user_load($contact['uf_id']));
  }
}

/**
 * Given a contact object, load or create then return a drupal user.
 *
 * @param object $contact
 *   CiviCRM Contact Object
 *
 * @param $is_active
 * @param bool $notify
 * @param bool $signin
 *
 * @throws Exception
 * @return object
 *   $user Drupal user object or FALSE.
 */
function civicrm_entity_action_create_user($contact, $is_active, $notify = FALSE, $signin = FALSE) {
  if (!is_array($contact)) {
    // Perhaps we should be accepting object rather than array here?
    $contact = (array) $contact;
  }
  // We'll use the civicrm sync mechanism to see if Civi can match the
  // contact to an existing user.
  //
  // Don't think this is a great approach but will use for now - could
  // just create the user but no great support for that yet.
  if (empty($contact['display_name']) || empty($contact['email'])) {
    $contact = civicrm_api('contact', 'getsingle', array(
      'version' => 3,
      'id' => $contact['id'],
      'sequential' => 1,
      'return' => 'email,display_name',
    ));
  }
  if (!is_string($contact['email']) && isset($contact['email'][0]->email)) {
    $contact['email'] = $contact['email'][0]->email;
  }
  // @TODO What happens if they don't have an email at this point?
  // An email is a pre-requisite for a Drupal account, so the action
  // fails if they don't have an email.
  $contact['display_name'] = trim(preg_replace("/[^A-Za-z0-9 ]/", '', truncate_utf8($contact['display_name'],60)));
  $params = array(
    'name' => $contact['display_name'],
    'mail' => $contact['email'],
    'email' => $contact['email'],
    'init' => $contact['email'],
  );

  // Check if the requested username is available.
  $errors = array();
  $config = CRM_Core_Config::singleton();
  $config->userSystem->checkUserNameEmailExists($params, $errors);
  if (!empty($errors)) {
    foreach ($errors as $error) {
      drupal_set_message(t($error), 'error');
    }
    return FALSE;
  }

  $params['cms_name'] = $params['name'] = $user['name'] = !empty($contact['display_name']) ? $contact['display_name'] : $params['mail'];
  $params['cms_pass'] = $user['pass'] = substr(str_shuffle("abcefghijklmnopqrstuvwxyz"), 0, 8);
  $params['status'] = $is_active;
  if ($notify) {
    $params['notify'] = TRUE;
  }

  $params['roles'] = array(
    DRUPAL_AUTHENTICATED_RID => 'authenticated user',
  );

  // Set $config->inCiviCRM = TRUE to prevent creating a duplicate
  // contact from user_save().
  $config = CRM_Core_Config::singleton();
  $config->inCiviCRM = TRUE;

  $user_object = user_save('', $params);
  $user_object->password = $user['pass'];

  $config->inCiviCRM = FALSE;

  // If selected in action configuration, notify the newly created
  // user & send registration link. Does not contain password in D7.
  if ($notify) {
    drupal_mail('user', 'register_no_approval_required', $params['mail'], NULL, array('account' => $user_object), variable_get('site_mail', 'noreply@example..com'));
  }

  // CiviCRM doesn't do this when created off CiviCRM Form.
  //
  // Note that we 'pretend' to be logging in to make it do a ufmatch
  // on just the email.
  CRM_Core_BAO_UFMatch::synchronizeUFMatch($user_object, $user_object->uid, $contact['email'], 'drupal', NULL, NULL, TRUE);

  // If selected in action configuration, automatically sign in the
  // current user.
  if ($signin) {
    global $user;
    $user = user_load($user_object->uid);
    watchdog('civicrm_entity', 'User %name logged in via CiviCRM Entity rule execution.', array('%name' => $user->name), WATCHDOG_INFO);
    $form_values = array('uid' => $user->uid);
    user_login_finalize($form_values);
  }

  return array('civicrm_user' => $user_object);
}

function civicrm_entity_query($type, $property, $value, $limit) {
  $return = entity_load($type, FALSE, array(
      $property => $value,
      'options' => array('limit' => $limit)
    ));
  return array('entity_fetched' => array_values($return));
}

/**
 * Info alteration callback for the entity query action.
 * @todo this is copy of rules_action_entity_query_info_alter
 *
 * @param $element_info
 * @param RulesAbstractPlugin $element
 */
function civicrm_entity_query_info_alter(&$element_info, RulesAbstractPlugin $element) {
  $element->settings += array('type' => NULL, 'property' => NULL);
  if ($element->settings['type']) {
    $element_info['parameter']['property']['options list'] = 'rules_action_entity_query_property_options_list';

    if ($element->settings['property']) {
      $wrapper = rules_get_entity_metadata_wrapper_all_properties($element);
      if (isset($wrapper->{$element->settings['property']}) &&
        $property = $wrapper->{$element->settings['property']}
      ) {
        $element_info['parameter']['value']['type'] = $property->type();
        $element_info['parameter']['value']['options list'] = $property->optionsList() ? 'rules_action_entity_query_value_options_list' : FALSE;
      }
    }
  }
  $element_info['provides']['entity_fetched']['type'] =
    'list<' . $element->settings['type'] . '>';
}

/**
 * Load or create user as appropriate.
 *
 * @param $entity
 * @param int $is_active
 * @param int $notify
 *
 * @return object
 */
function civicrm_entity_action_load_create_user($entity, $is_active = 0, $notify = 0) {
  if ($user = civicrm_entity_action_load_user($entity)) {
    if ($is_active && !$user['civicrm_user']->status) {
      $user['civicrm_user']->status = $is_active;
      $user['civicrm_user']->save;
    }
    return $user;
  }
  return civicrm_entity_action_create_user((array) $entity, $is_active, $notify);
}

/**
 * @param $user
 *
 * @param null $email
 *
 * @return mixed
 */
function civicrm_entity_action_load_create_contact($user, $email = NULL) {
  try {
    return civicrm_entity_action_load_contact($user);
  }
  catch (CiviCRM_API3_Exception $e) {
    $ufMatch = CRM_Core_BAO_UFMatch::synchronizeUFMatch($user, $user->uid, ($email ? $email : $user->mail), 'Drupal', FALSE, 'Individual');
    $entities = entity_load('civicrm_contact', array($ufMatch->contact_id));
    return array('civicrm_contact' => reset($entities));
  }

}

/**
 * @param $user
 *
 * @return mixed
 * @throws CiviCRM_API3_Exception
 */
function civicrm_entity_action_load_contact($user) {
  if (!civicrm_initialize()) {
    return;
  }
  $contact_id = civicrm_api3('uf_match', 'getvalue', array(
    'uf_id' => $user->uid,
    'return' => 'contact_id',
    'domain_id' => CRM_Core_Config::domainID()
  ));
  $entities = entity_load('civicrm_contact', array($contact_id));
  return array('civicrm_contact' => reset($entities));
}

/**
 * gt location options
 * @return array
 */
function civicrm_entity_get_locations() {
  if (!civicrm_initialize()) {
    return array();
  }
  $locations = civicrm_api3('address', 'getoptions', array('field' => 'location_type_id'));
  $locations = $locations['values'];
  return array('0' => 'Primary') + $locations;
}

/**
 * @param $contact
 * @param $location_type_id
 *
 * @return array
 */
function civicrm_entity_contact_has_location_element_email(&$contact, $location_type_id) {
  if (!empty($contact->email)) {
    return TRUE;
  }
  $email = civicrm_entity_contact_has_location_element('email', $contact, $location_type_id);
  if (!empty($email['civicrm_email']->email)) {
    $contact->email = $email['civicrm_email']->email;
    return TRUE;
  }
  return FALSE;
}

/**
 * @param $contact
 * @param $location_type_id
 *
 * @return array
 */
function civicrm_entity_contact_get_email($contact, $location_type_id) {
  return civicrm_entity_contact_get_location_element('email', $contact, $location_type_id);
}

/**
 * @param $contact
 * @param $location_type_id
 *
 * @return array|bool
 */
function civicrm_entity_contact_get_location_element($entity, &$contact, $location_type_id) {
  $params = array(
    'contact_id' => $contact->id,
    'sequential' => 1,
    'on_hold' => 0
  );
  if ($location_type_id) {
    $params['location_type_id'] = $location_type_id;
  }
  else {
    $params['is_primary'] = 1;
  }
  $result = civicrm_api3($entity, 'get', $params);
  if (!$result['count']) {
    return array('civicrm_' . $entity => '');
  }
  return array('fetched_' . $entity => $result['values'][0]['email']);
}

/**
 * @param $contact
 * @param $subject
 * @param $message_text
 * @param $message_html
 * @param null $from
 */
function civicrm_entity_contact_send_email($contact, $subject, $message_text, $message_html, $from = NULL) {
  $email = civicrm_api3('email', 'get', array(
      'contact_id' => $contact->id,
      'is_primary' => 1,
      'on_hold' => 0,
      'sequential' => 1
    ));
  if (!$email['count']) {
    watchdog('civicrm_entity_rules', 'no email could be sent to !contact_id', array('!contact_id' => $contact->id));
  }
  $params = array();
  $params['from'] = !empty($from) ? str_replace(array(
    "\r",
    "\n"
  ), '', $from) : 'Admin';
  $params['toEmail'] = $email['values'][0]['email'];
  $params['subject'] = $subject;
  $params['text'] = $message_text;
  $params['html'] = $message_html;
  CRM_Utils_Mail::send($params);
  civicrm_api3('activity', 'create', array(
      'activity_type_id' => 'Email',
      'source_contact_id' => $contact->id,
      'target_contact_id' => $contact->id,
      'subject' => $subject,
      'details' => $message_html
    ));
}

/**
 * Implement the post hook and fire the corresponding rules event.
 *
 * @param $op
 * @param $object_name
 * @param $object_id
 * @param $object_ref
 */
function civicrm_entity_civicrm_post($op, $object_name, $object_id, &$object_ref) {
  if (!module_exists('rules')) {
    return;
  }
  $contact_types = array(
    'Individual',
    'Household',
    'Organization',
  );
  if (in_array($object_name, $contact_types)) {
    $object_name = 'Contact';
  }

  $valid_objects = _civicrm_entity_enabled_entities();
  $entity_name = _civicrm_entity_get_entity_name_from_camel($object_name);
  if (!in_array($entity_name, $valid_objects, TRUE)) {
    return;
  }
  $event_name = NULL;
  switch ($op) {

    case 'create':
    case 'edit':
      $event_name = 'civicrm_' . $entity_name . "_{$op}";
      break;

    /*
     *  Here we are checking if the contact entity is being deleted
     *  AND if the contact has sent to the trash already. If the
     *  contact has been sent to the trash, we want to permanently
     *  delete it. If not, we will just fire the "update" event to
     *  let the subscribed rules know that the "is_delete" flag has
     *  changed.
     */
    case 'delete':
      if($entity_name == 'contact') {
        if($object_ref->is_deleted == 1) {
          $event_name = 'civicrm_' . $entity_name . "_{$op}";
        }
        else {
          //we are receiving a reference to the contact object before the flag has changed. So we need to force it to change.
          $object_ref->is_deleted = 1;
          $event_name = 'civicrm_' . $entity_name . "_edit";
        }
      }
      else {
        $event_name = 'civicrm_' . $entity_name . "_{$op}";
      }
      break;

    //We need to alert subscribed rules that the "is_delete" flag has changed.
    case 'restore':
      //we are receiving a reference to the contact object before the flag has changed. So we need to force it to change.
      $object_ref->is_deleted = 0;
      $event_name = 'civicrm_' . $entity_name . "_edit";
      break;

    default:
      break;

  }
  if ($entity_name == 'entity_tag') {
    // Argh entity tag is completely non-standard!!!
    // @see CRM-11933
    foreach ($object_ref[0] as $entity_tag) {
      $object = new CRM_Core_BAO_EntityTag();
      $object->entity_id = $entity_tag;
      $object->entity_table = 'civicrm_contact';
      $object->tag_id = $object_id;
      if ($object->find(TRUE)) {
        // This find is probably not necessary but until more testing
        // on the tag create is done I will.
        rules_invoke_event($event_name, $object);
      }
    }
  }
  else {
    if ($event_name) {
      rules_invoke_event($event_name, $object_ref);
    }
  }
}

/**
 * Convert possibly camel name to underscore separated entity name.
 *
 * @see _civicrm_api_get_entity_name_from_camel()
 *
 * @TODO Why don't we just call the above function directly?
 * Because the function is officially 'likely' to change as it is an internal api function and calling api functions directly is explicitly not supported
 *
 * @param string $entity
 *   Entity name in various formats e.g:
 *     Contribution => contribution,
 *     OptionValue => option_value,
 *     UFJoin => uf_join.
 *
 * @return string
 *   $entity entity name in underscore separated format
 */
function _civicrm_entity_get_entity_name_from_camel($entity) {
  if ($entity == strtolower($entity)) {
    return $entity;
  }
  else {
    $entity = ltrim(strtolower(
      str_replace('U_F', 'uf',
        // That's CamelCase, beside an odd UFCamel that is expected as uf_camel
        preg_replace('/(?=[A-Z])/', '_$0', $entity)
      )), '_');
  }
  return $entity;
}

/**
 * Load contact entity according to user id.
 *
 * @param $data
 * @param array $options
 * @param $name
 * @param $type
 * @param $info
 *
 * @return null
 */
function civicrm_entity_user_contact_get($data, array $options, $name, $type, $info) {
  if (!module_exists('civicrm') || !function_exists('civicrm_initialize')) {
    return;
  }
  if (!civicrm_initialize()) {
    return;
  }

  $domain_id = civicrm_api('domain', 'getvalue', array(
    'version' => 3,
    'return' => 'id',
    'current_domain' => TRUE,
  ));
  $contact = civicrm_api('uf_match', 'getsingle', array(
    'version' => 3,
    'return' => 'contact_id',
    'uf_id' => $data->uid,
    'domain_id' => $domain_id,
  ));

  if (!empty($contact['contact_id'])) {
    $entity = entity_load('civicrm_contact', array($contact['contact_id']));
    return $entity[$contact['contact_id']];
  }
  else {
    return NULL;
  }
}

/**
 * Implements hook_rules_action_info_alter
 * I can't seem to get my info_alter function called by hook so am doing this hacky intercept
 * to call my function (& then go back to the main function if not a CiviCRM entity
 */
function civicrm_entity_rules_action_info_alter(&$info) {
  $info['entity_create']['callbacks']['info_alter'] = 'civicrm_entity_rules_action_entity_create_info_alter';
}

/**
 * Info alteration callback for the entity create action.
 * Here we add a tonne of fields to civicrm entity create
 */
function civicrm_entity_rules_action_entity_create_info_alter(&$element_info, RulesAbstractPlugin $element) {
  if (empty($element->settings['type']) ||
    substr($element->settings['type'], 0, 8) != 'civicrm_'
  ) {
    module_load_include('inc', 'rules', 'modules/entity.eval');
    return rules_action_entity_create_info_alter($element_info, $element);
  }
  module_load_include('inc', 'rules', 'modules/data.rules');
  $civicrm_entity = str_replace('civicrm_', '', $element->settings['type']);
  if (!empty($element->settings['type']) &&
    entity_get_info($element->settings['type'])
  ) {
    $wrapper = entity_metadata_wrapper($element->settings['type']);
    // Add the data type's needed parameter for loading to the parameter info.
    $priority_fields = array('type');
    foreach ($wrapper as $name => $child) {
      $info = $child->info();
      if (substr($info['type'], 0, 8) == 'civicrm_') {
        //we are already showing id lets not show entity too
        continue;
      }
      $info = array_merge(array('type' => 'text'), $info);
      // Prefix parameter names to avoid name clashes with existing parameters.
      $element_info['parameter']['param_' .
      $name] = array_intersect_key($info, array_flip(array(
            'type',
            'label',
            'description'
          )));
      $element_info['parameter']['param_' .
      $name]['options list'] = $child->optionsList() ? 'rules_action_entity_parameter_options_list' : FALSE;
      $element_info['parameter']['param_' .
      $name]['optional'] = $element_info['parameter']['param_' .
      $name]['allow null'] = empty($info['required']);
      $element_info['parameter']['param_' . $name]['default mode'] = 'selector';
      if (!empty($info['required'])) {
        $priority_fields[] = 'param_' . $name;
      }
    }
    unset($element_info['parameter']['param_type']);
    if (in_array($civicrm_entity, array('participant', 'membership'))) {
      $element_info['parameter']['param_civicrm_contribution'] = array(
        'type' => 'civicrm_contribution',
        'label' => 'CiviCRM Contribution',
        'description' => t('Optional CiviCRM contribution for paid ' .
          $civicrm_entity),
        'optional' => TRUE,
        'allow null' => TRUE,
        'default mode' => 'selector',
      );
      $priority_fields[] = 'param_civicrm_contribution';
    }

    $element_info['parameter'] = array_merge(array_flip($priority_fields), $element_info['parameter']);
    foreach (civicrm_entity_get_custom_fields($civicrm_entity) as $fieldname => $field) {
      $element_info['parameter'][$fieldname] = array(
        'type' => $field['type'],
        'label' => $field['label'],
        'optional' => TRUE,
        'default mode' => 'selector',
        'allow null' => TRUE,
      );
    }

    $element_info['provides']['entity_created']['type'] = $element->settings['type'];
    if (($bundleKey = $wrapper->entityKey('bundle')) &&
      isset($element->settings['param_' . $bundleKey])
    ) {
      $element_info['provides']['entity_created']['bundle'] = $element->settings[
      'param_' . $bundleKey];
    }
  }
}

/**
 * @param $entity
 */
function civicrm_entity_get_custom_fields($entity, $types = array(
    'Integer' => 'integer',
    'String' => 'text',
    'Date' => 'date'
  )) {
  if (!civicrm_initialize()) {
    return array();
  }
  $fields = civicrm_api3($entity, 'getfields', array(
      'action' => 'create',
      'getoptions' => TRUE
    ));
  $fields = $fields['values'];
  foreach ($fields as $field_name => $field) {
    if (substr($field_name, 0, 7) != 'custom_' ||
      !in_array($field['data_type'], array_keys($types))
    ) {
      unset($fields[$field_name]);
    }
    else {
      $fields[$field_name]['type'] = $types[$field['data_type']];
    }
  }
  return $fields;
}

/**
 * Implements hook_theme()
 *
 * Lets Drupal know to look for templates for the entity types
 *
 * @return themes
 */

function civicrm_entity_theme() {
  $civicrm_entities = _civicrm_entity_enabled_entities();
  $themes = array();

  foreach ($civicrm_entities as $key => $value) {
    $dashkey = str_replace('_', '-', $key);
    $themes[$key] = array(
      'render element' => 'elements',
      'template' => $dashkey,
      'path' => drupal_get_path('module', 'civicrm_entity') . '/templates',
    );
  }

  return $themes;
}

/**
 * Loads UI controller and generates view pages for civicrm entities
 *
 * @param integer id
 * @param string entity_type
 * @param string view_mode
 *
 * @return string content
 */

function civicrm_entity_page_view($id, $entity_type) {
  $content = "";
  $entity = entity_load($entity_type, array($id));

  if (!empty($entity)) {
    $entity = $entity[$id];
    $controller = entity_get_controller($entity_type);
    if($entity_type == 'civicrm_contact') {
      //for some reason the is_deleted column of the contact record is coming to the entity
      // as contact_is_deleted ...special handling to have the page value set properly
      $entity->is_deleted = $entity->contact_is_deleted;
     }

    $content = $controller->view(array($id => $entity));
  }
  else {
    $content = '<p>No ' . $entity_type . ' record found for id: ' . $id . '</p>';
  }
  $formatted_entity_title = ucwords(str_replace('_', ' ', $entity_type));
  drupal_set_title($formatted_entity_title . ' ' . $id);

  return $content;
}

/**
 * Granular per-entity CRUD access control
 * @param $op
 * @param $entity
 *
 * @return TRUE/FALSE
 */
function  civicrm_entity_op_access($op, $entity) {
  if ($op == 'view') {
    switch ($entity) {
      case "civicrm_contact":
      case "civicrm_address":
      case "civicrm_email":
        return user_access('view all contacts');
      case "civicrm_activity":
        return user_access('view all activities');
      case "civicrm_event":
        return user_access('view event info');
      case "civicrm_contribution":
        return user_access('administer CiviCRM') &&
        user_access('access CiviContribute');
      case "civicrm_participant":
        return user_access('view event participants');
      case "civicrm_relationship":
        return user_access('view all contacts') &&
        user_access('administer CiviCRM');
      case "civicrm_relationship_type":
        return user_access('administer CiviCRM');
      case "civicrm_entity_tag":
        return user_access('administer CiviCRM');
      case "civicrm_membership":
        return user_access('access CiviMember');
      case "civicrm_membership_type":
        return user_access('administer CiviCRM') &&
        user_access('access CiviMember');
      case "civicrm_group":
        return user_access('administer CiviCRM');
      case "civicrm_grant":
        return user_access('access CiviGrant') &&
        user_access('administer CiviCRM');
      case "civicrm_tag":
        return user_access('administer Tagsets') &&
        user_access('administer CiviCRM');
      case "civicrm_financial_type":
        return user_access('access CiviContribute') &&
        user_access('administer CiviCRM');
      case "civicrm_price_set_entity":
      case "civicrm_price_set":
      case "civicrm_price_field":
      case "civicrm_price_field_value":
        return user_access('administer CiviCRM');
      default:
        return FALSE;
    }
  }
  if ($op == 'edit' || $op == 'create') {
    switch ($entity) {
      case "civicrm_contact":
      case "civicrm_address":
      case "civicrm_email":
        return user_access('edit all contacts');
      case "civicrm_activity":
        return user_access('view all activities');
      case "civicrm_event":
        return user_access('edit all events');
      case "civicrm_contribution":
        return user_access('administer CiviCRM') &&
        user_access('edit contributions');
      case "civicrm_participant":
        return user_access('edit event participants') &&
        user_access('access CiviEvent');
      case "civicrm_relationship":
        return user_access('edit all contacts') &&
        user_access('administer CiviCRM');
      case "civicrm_relationship_type":
        return user_access('administer CiviCRM');
      case "civicrm_entity_tag":
        return user_access('administer CiviCRM');
      case "civicrm_membership":
        return user_access('access CiviMember') &&
        user_access('edit memberships');
      case "civicrm_membership_type":
        return user_access('administer CiviCRM') &&
        user_access('access CiviMember');
      case "civicrm_group":
        return user_access('administer CiviCRM') && user_access('edit groups');
      case "civicrm_grant":
        return user_access('access CiviGrant') &&
        user_access('administer CiviCRM') && user_access('edit grants');
      case "civicrm_tag":
        return user_access('administer Tagsets') &&
        user_access('administer CiviCRM');
      case "civicrm_financial_type":
        return user_access('access CiviContribute') &&
        user_access('administer CiviCRM');
      case "civicrm_price_set_entity":
      case "civicrm_price_set":
      case "civicrm_price_field":
      case "civicrm_price_field_value":
        return user_access('administer CiviCRM');
      default:
        return FALSE;
    }
  }

  if ($op == 'delete') {
    switch ($entity) {
      case "civicrm_contact":
      case "civicrm_address":
      case "civicrm_email":
        return user_access('delete contacts');
      case "civicrm_activity":
        return user_access('delete activities');
      case "civicrm_event":
        return user_access('edit all events') &&
        user_access('delete in CiviEvent');
      case "civicrm_contribution":
        return user_access('administer CiviCRM') &&
        user_access('edit contributions') &&
        user_access('delete in CiviContribute');
      case "civicrm_participant":
        return user_access('edit event participants') &&
        user_access('access CiviEvent');
      case "civicrm_relationship":
        return user_access('edit all contacts') &&
        user_access('administer CiviCRM') && user_access('delete contacts');
      case "civicrm_relationship_type":
        return user_access('administer CiviCRM');
      case "civicrm_entity_tag":
        return user_access('administer CiviCRM');
      case "civicrm_membership":
        return
          user_access('access CiviMember') && user_access('edit memberships') &&
          user_access('delete in CiviMember');
      case "civicrm_membership_type":
        return user_access('administer CiviCRM') &&
        user_access('access CiviMember') && user_access('delete in CiviMember');
      case "civicrm_group":
        return user_access('administer CiviCRM') && user_access('edit groups');
      case "civicrm_grant":
        return user_access('access CiviGrant') &&
        user_access('administer CiviCRM') && user_access('edit grants') &&
        user_access('delete in CiviGrant');
      case "civicrm_tag":
        return user_access('administer Tagsets') &&
        user_access('administer CiviCRM');
      case "civicrm_financial_type":
        return user_access('access CiviContribute') &&
        user_access('administer CiviCRM') &&
        user_access('delete in CiviContribute');
      case "civicrm_price_set_entity":
      case "civicrm_price_set":
      case "civicrm_price_field":
      case "civicrm_price_field_value":
        return user_access('administer CiviCRM');
      default:
        return FALSE;
    }
  }

}
/**
 * Implements hook_ds_field_settings_form().
 */
function civicrm_entity_ds_field_settings_form($field) {
  return ds_ds_field_settings_form($field);
}

/**
 * Implements hook_ds_field_format_summary().
 */
function civicrm_entity_ds_field_format_summary($field) {
  return ds_ds_field_format_summary($field);
}

/*
 * Implementes hook_form_alter()
 */
function civicrm_entity_form_alter(&$form, &$form_state, $form_id){
// For the manage display form, add a submit handler to make display suite custom civicrm "field" settings stick
  if($form_id == 'field_ui_display_overview_form' ) {
    if (!civicrm_initialize(TRUE)) {
       return;
    }
    $entities = _civicrm_entity_enabled_entities();
    $entity_type = $form['#entity_type'];
    if(array_key_exists($entity_type,$entities)) {
      $submits = array();
      $submits[] = '_civicrm_entity_manage_display_submit';
      foreach($form['#submit'] as $submit_callback){
        $submits[] = $submit_callback;
      }
      $form['#submit'] = $submits;
    }

  }
}

/*
 * Custom submit handler
 * updates bundle visibility settings if a display suite layout is used
 *
 */
function _civicrm_entity_manage_display_submit(&$form, &$form_state) {
  if($form_state['values']['additional_settings']['layout']!=''){
    $entity_type = $form['#entity_type'];
    $bundle = $form['#bundle'];
    $bundle_settings = field_bundle_settings($entity_type, $bundle);

    foreach($bundle_settings['extra_fields']['display'] as $key => $field) {
      $form_state['values']['fields'][$key]['type'] = 'visible';
    }
  }
}

/*
 *  Implements hook_field_extra_fields_alter()
 *  put civicrm properties on the manage fields form for weight based ordering of edit form elements
 *
 */
function civicrm_entity_field_extra_fields_alter(&$info) {
  if (!civicrm_initialize(TRUE)) {
    return;
  }
  $entities = _civicrm_entity_enabled_entities();
  foreach ($entities as $drupal_entity => $civicrm_entity) {
    $properties[$drupal_entity]['properties'] = _civicrm_entity_getproperties($civicrm_entity, 'property_info');

    foreach($info[$drupal_entity][$drupal_entity]['display'] as $name => $props) {
      $info[$drupal_entity][$drupal_entity]['form'][$name] = $props;
    }
  }

}

/*
 *  Implements hook_ds_fields_info()
 *  setup custom display suite "field" handling for CiviCRM properties
 *
 */
function civicrm_entity_ds_fields_info($entity_type) {
  $fields = array();
   if (!civicrm_initialize(TRUE)) {
    return;
  }
  $properties = _civicrm_entity_getproperties(substr($entity_type,8), 'property_info');

  // Basic wrapper and class settings for all CiviCRM properties, also makes the label visibility work
  foreach($properties as $name => $settings) {
    $fields[$entity_type][$name] = array(
      'title' => $settings['label'],
      'field_type' => 2,
      'function' => '_civicrm_entity_render_fields',
      'properties' => array(
        'settings' => array(
          'wrapper' => array('type' => 'textfield', 'description' => t('Eg: h1, h2, p')),
          'class' => array('type' => 'textfield', 'description' => t('Put a class on the wrapper. Eg: block-title')),
        ),
       'default' => array('wrapper' => 'div', 'class' => 'civicrm-field'),
      ),
    );
    // could do some date formatter logic all at one here
    /*if(isset($settings['mysql_type') && $settings['mysql_type'] == 'datetime') {
       $fields[$entity_type][$name]['date']['date'] = TRUE;
       $fields[$entity_type][$name]['date']['granularity'] = $settings['granularity'];
    }*/
  }



  //add specific property formatters
  _civicrm_entity_add_formatters($entity_type,$fields);

  if (isset($fields[$entity_type])) {
    return array($entity_type => $fields[$entity_type]);
  }
}

function _civicrm_entity_add_formatters($entity_type,&$fields) {
   switch($entity_type) {
   case 'civicrm_activity':
     _civicrm_entity_activity_formatters($fields);
     break;
   case 'civicrm_address':
     _civicrm_entity_address_formatters($fields);
     break;
   case 'civicrm_contact':
     _civicrm_entity_contact_formatters($fields);
     break;
   case 'civicrm_contribution':
     _civicrm_entity_contribution_formatters($fields);
     break;
   case 'civicrm_email':
     _civicrm_entity_email_formatters($fields);
     break;
   case 'civicrm_entity_tag':
     _civicrm_entity_entity_tag_formatters($fields);
     break;
   case 'civicrm_event':
     _civicrm_entity_event_formatters($fields);
     break;
   case 'civicrm_financial_type':
     _civicrm_entity_financial_type_formatters($fields);
     break;
   case 'civicrm_grant':
     _civicrm_entity_grant_formatters($fields);
     break;
   case 'civicrm_group':
     _civicrm_entity_group_formatters($fields);
     break;
   case 'civicrm_membership':
     _civicrm_entity_membership_formatters($fields);
     break;
   case 'civicrm_membership_type':
     _civicrm_entity_membership_type_formatters($fields);
     break;
   case 'civicrm_participant':
     _civicrm_entity_participant_formatters($fields);
     break;
   case 'civicrm_price_field':
     _civicrm_entity_price_field_formatters($fields);
     break;
   case 'civicrm_price_field_value':
     _civicrm_entity_price_field_value_formatters($fields);
     break;
   case 'civicrm_price_set':
     _civicrm_entity_price_set_formatters($fields);
     break;
   case 'civicrm_relationship':
     _civicrm_entity_relationship_formatters($fields);
     break;
   case 'civicrm_relationship_type':
     _civicrm_entity_relationship_type_formatters($fields);
     break;
   case 'civicrm_tag':
     _civicrm_entity_tag_formatters($fields);
     break;
   }
}

function _civicrm_entity_activity_formatters(&$fields){
  $link_fields = array(
    array(
      'link_field' => 'source_contact_id',
      'target' => 'civicrm_contact',
    ),
     array(
      'link_field' => 'assignee_contact_id',
      'target' => 'civicrm_contact',
    ),
     array(
      'link_field' => 'target_contact_id',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'relationship_id',
      'target' => 'civicrm_relationship',
    ),
    array(
      'link_field' => 'parent_id',
      'target' => 'civicrm_activity',
    ),
    array(
      'link_field' => 'original_id',
      'target' => 'civicrm_activity',
    ),
  );
  _civicrm_entity_link_addformatters('civicrm_activity',$link_fields,$fields);
  $option_fields = array(
    'activity_type_id',
    'status_id',
    'medium_id',
    'priority_id',
  );
  _civicrm_entity_option_addformatters('civicrm_activity',$option_fields,$fields);
  $yes_no_fields = array(
    'is_auto',
    'is_current_revision',
    'is_test',
    'is_deleted',
  );
  _civicrm_entity_yesno_addformatters('civicrm_activity',$yes_no_fields,$fields);
}

function _civicrm_entity_address_formatters(&$fields){
  $link_fields = array(
    array(
      'link_field' => 'contact_id',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'contact_id_contact',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'master_id',
      'target' => 'civicrm_contact',
    ),
  );
  _civicrm_entity_link_addformatters('civicrm_address',$link_fields,$fields);
  $option_fields = array(
    'location_type_id',
    'county_id',
    'state_province_id',
    'country_id',
  );
  _civicrm_entity_option_addformatters('civicrm_address',$option_fields,$fields);
  $yes_no_fields = array(
    'is_primary',
    'is_billing',
  );
  _civicrm_entity_yesno_addformatters('civicrm_address',$yes_no_fields,$fields);
}

function _civicrm_entity_contact_formatters(&$fields){
  $link_fields = array(
    array(
      'link_field' => 'employer_id_contact',
      'target' => 'civicrm_contact',
    ),
  );
  _civicrm_entity_link_addformatters('civicrm_contact',$link_fields,$fields);
  $option_fields = array(
    'preferred_communication_method',
    'prefix_id',
    'suffix_id',
    'communication_style_id',
    'gender_id',
  );
  _civicrm_entity_option_addformatters('civicrm_contact',$option_fields,$fields);
  $yes_no_fields = array(
    'is_deceased',
    'do_not_email',
    'do_not_phone',
    'do_not_sms',
    'do_not_trade',
    'do_not_mail',
    'is_opt_out',
    'is_deleted',
    'contact_is_deleted',
  );
  _civicrm_entity_yesno_addformatters('civicrm_contact',$yes_no_fields,$fields);
}

function _civicrm_entity_contribution_formatters(&$fields){
  $link_fields = array(
    array(
      'link_field' => 'contact_id_contact',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'contact_id',
      'target' => 'civicrm_contact',
    ),
  );
  _civicrm_entity_link_addformatters('civicrm_contribution',$link_fields,$fields);
  $option_fields = array(
   // 'cancel_reason',
    'financial_type_id',
    'contribution_status_id',
  );
  _civicrm_entity_option_addformatters('civicrm_contribution',$option_fields,$fields);
  $yes_no_fields = array(
    'is_test',
    'is_pay_later',

  );
  _civicrm_entity_yesno_addformatters('civicrm_contribution',$yes_no_fields,$fields);
}

function _civicrm_entity_email_formatters(&$fields){
  $link_fields = array(
    array(
      'link_field' => 'contact_id',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'contact_id_contact',
      'target' => 'civicrm_contact',
    ),

  );
  _civicrm_entity_link_addformatters('civicrm_email',$link_fields,$fields);
  $option_fields = array(
    'location_type_id',
  );
  _civicrm_entity_option_addformatters('civicrm_email',$option_fields,$fields);
  $yes_no_fields = array(
    'is_primary',
    'is_billing',
    'on_hold',
    'is_bulkmail',
  );
  _civicrm_entity_yesno_addformatters('civicrm_email',$yes_no_fields,$fields);
}

function _civicrm_entity_entity_tag_formatters(&$fields){
  $link_fields = array(
    array(
      'link_field' => 'tag_id',
      'target' => 'civicrm_tag',
    ),
  );
  _civicrm_entity_link_addformatters('civicrm_entity_tag',$link_fields,$fields);
  $option_fields = array(
  );
 // _civicrm_entity_option_addformatters('civicrm_entity_tag',$option_fields,$fields);
  $yes_no_fields = array(
  );
 // _civicrm_entity_yesno_addformatters('civicrm_entity_tag',$yes_no_fields,$fields);
}

function _civicrm_entity_event_formatters(&$fields){
  $link_fields = array(
    array(
      'link_field' => 'created_id_contact',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'created_id',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'parent_event_id',
      'target' => 'civicrm_event',
    ),
  );
  _civicrm_entity_link_addformatters('civicrm_event',$link_fields,$fields);
  $option_fields = array(
   // 'cancel_reason',
    'event_type_id',
    'financial_type_id',
    'default_role_id',
  );
  _civicrm_entity_option_addformatters('civicrm_event',$option_fields,$fields);
  $yes_no_fields = array(
    'is_public',
    'is_pay_later',
    'is_online_registration',
    'is_monetary',
    'is_map',
    'is_active',
    'is_show_location',
    'is_partial_payment',
    'is_multiple_registrations',
    'allow_same_participant_emails',
    'has_waitlist',
    'requires_approval',
    'is_template',
    'is_share',
    'is_confirm_enabled',
  );
  _civicrm_entity_yesno_addformatters('civicrm_event',$yes_no_fields,$fields);
}

function _civicrm_entity_financial_type_formatters(&$fields){
  $link_fields = array(
  );
  //_civicrm_entity_link_addformatters('civicrm_financial_type',$link_fields,$fields);
  $option_fields = array(
  );
 // _civicrm_entity_option_addformatters('civicrm_financial_type',$option_fields,$fields);
  $yes_no_fields = array(
  'is_reserved',
  'is_active',
  'is_deductible',
  );
  _civicrm_entity_yesno_addformatters('civicrm_financial_type',$yes_no_fields,$fields);
}

function _civicrm_entity_grant_formatters(&$fields){
  $link_fields = array(
    array(
      'link_field' => 'contact_id',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'contact_id_contact',
      'target' => 'civicrm_contact',
    ),
  );
  _civicrm_entity_link_addformatters('civicrm_grant',$link_fields,$fields);
  $option_fields = array(
    'status_id',
    'financial_type_id',
    'grant_type_id',
  );
  _civicrm_entity_option_addformatters('civicrm_grant',$option_fields,$fields);
  $yes_no_fields = array(
    'grant_report_received',
  );
  _civicrm_entity_yesno_addformatters('civicrm_grant',$yes_no_fields,$fields);
}

function _civicrm_entity_group_formatters(&$fields){
  $link_fields = array(
    array(
      'link_field' => 'created_id',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'created_id_contact',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'modified_id',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'modified_id_contact',
      'target' => 'civicrm_contact',
    ),
  );
  _civicrm_entity_link_addformatters('civicrm_group',$link_fields,$fields);
  $option_fields = array(
  );
 // _civicrm_entity_option_addformatters('civicrm_group',$option_fields,$fields);
  $yes_no_fields = array(
    'is_active',
    'is_hidden',
    'is_reserved'
  );
  _civicrm_entity_yesno_addformatters('civicrm_group',$yes_no_fields,$fields);
}

function _civicrm_entity_membership_formatters(&$fields){
  $link_fields = array(
    array(
      'link_field' => 'contact_id',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'contact_id_contact',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'owner_membership_id',
      'target' => 'civicrm_membership',
    ),
  );
  _civicrm_entity_link_addformatters('civicrm_membership',$link_fields,$fields);
  $option_fields = array(
    'membership_type_id',
    'status_id',
  );
  _civicrm_entity_option_addformatters('civicrm_membership',$option_fields,$fields);
  $yes_no_fields = array(
    'is_test',
    'is_pay_later',
    'is_override',
  );
  _civicrm_entity_yesno_addformatters('civicrm_membership',$yes_no_fields,$fields);
}

function _civicrm_entity_membership_type_formatters(&$fields){
  $link_fields = array(
    array(
      'link_field' => 'member_of_contact_id',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'member_of_contact_id_contact',
      'target' => 'civicrm_contact',
    ),
  );
  _civicrm_entity_link_addformatters('civicrm_membership_type',$link_fields,$fields);
  $option_fields = array(
    'financial_type_id',

  );
  _civicrm_entity_option_addformatters('civicrm_membership_type',$option_fields,$fields);
  $yes_no_fields = array(
    'is_active',
    'auto_renew',
  );
  _civicrm_entity_yesno_addformatters('civicrm_membership_type',$yes_no_fields,$fields);
}

function _civicrm_entity_participant_formatters(&$fields){
  $link_fields = array(
    array(
      'link_field' => 'contact_id',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'contact_id_contact',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'event_id',
      'target' => 'civicrm_event',
    ),
    array(
      'link_field' => 'event_id_event',
      'target' => 'civicrm_event',
    ),
    array(
      'link_field' => 'registered_by_id',
      'target' => 'civicrm_contact',
    ),
  );
  _civicrm_entity_link_addformatters('civicrm_participant',$link_fields,$fields);
  $option_fields = array(
    'status_id',
    'role_id',
  );
  _civicrm_entity_option_addformatters('civicrm_participant',$option_fields,$fields);
  $yes_no_fields = array(
    'is_test',
    'is_pay_later',
    'must_wait'
  );
  _civicrm_entity_yesno_addformatters('civicrm_participant',$yes_no_fields,$fields);
}

function _civicrm_entity_price_field_formatters(&$fields){
  $link_fields = array(
    array(
      'link_field' => 'price_set_id',
      'target' => 'civicrm_price_set',
    ),
  );
  _civicrm_entity_link_addformatters('civicrm_price_field',$link_fields,$fields);
  $option_fields = array(
    'visibility_id',

  );
  _civicrm_entity_option_addformatters('civicrm_price_field',$option_fields,$fields);
  $yes_no_fields = array(
    'is_enter_qty',
    'is_display_amounts',
    'is_active',
    'is_required',
  );
  _civicrm_entity_yesno_addformatters('civicrm_price_field',$yes_no_fields,$fields);
}

function _civicrm_entity_price_field_value_formatters(&$fields){
  $link_fields = array(
    array(
      'link_field' => 'price_field_id',
      'target' => 'civicrm_price_field',
    ),
    array(
      'link_field' => 'membership_type_id',
      'target' => 'civicrm_membership_type',
    ),
  );
  _civicrm_entity_link_addformatters('civicrm_price_field_value',$link_fields,$fields);
  $option_fields = array(
    'financial_type_id',

  );
  _civicrm_entity_option_addformatters('civicrm_price_field_value',$option_fields,$fields);
  $yes_no_fields = array(
     'is_default',
     'is_active',
  );
  _civicrm_entity_yesno_addformatters('civicrm_price_field_value',$yes_no_fields,$fields);
}

function _civicrm_entity_price_set_formatters(&$fields){
  $link_fields = array(
  );
  //_civicrm_entity_link_addformatters('civicrm_price_set',$link_fields,$fields);
  $option_fields = array(
  );
  _civicrm_entity_option_addformatters('civicrm_price_set',$option_fields,$fields);
  $yes_no_fields = array(
    'is_active',
    'is_quick_config',
    'is_reserved',
  );
  _civicrm_entity_yesno_addformatters('civicrm_price_set',$yes_no_fields,$fields);
}

function _civicrm_entity_relationship_formatters(&$fields){
  $link_fields = array(
    array(
      'link_field' => 'contact_id_a',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'contact_id_a_contact',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'contact_id_b',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'contact_id_b_contact',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'relationship_type_id',
      'target' => 'civicrm_relationship_type',
    ),
  );
  _civicrm_entity_link_addformatters('civicrm_relationship',$link_fields,$fields);
  $option_fields = array(
  );
  //_civicrm_entity_option_addformatters('civicrm_relationship',$option_fields,$fields);
  $yes_no_fields = array(
    'is_active',
    'is_permission_a_b',
    'is_permission_b_a'
  );
  _civicrm_entity_yesno_addformatters('civicrm_relationship',$yes_no_fields,$fields);
}

function _civicrm_entity_relationship_type_formatters(&$fields){
  $link_fields = array(
  );
  // _civicrm_entity_link_addformatters('civicrm_relationship_type',$link_fields,$fields);
  $option_fields = array(
    'contact_sub_type_a',
    'contact_sub_type_b',
  );
  _civicrm_entity_option_addformatters('civicrm_relationship_type',$option_fields,$fields);
  $yes_no_fields = array(
    'is_reserved',
    'is_active',
  );
  _civicrm_entity_yesno_addformatters('civicrm_relationship_type',$yes_no_fields,$fields);
}

function _civicrm_entity_tag_formatters(&$fields){
  $link_fields = array(
    array(
      'link_field' => 'created_id',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'created_id_contact',
      'target' => 'civicrm_contact',
    ),
    array(
      'link_field' => 'parent_id',
      'target' => 'civicrm_tag',
    ),
  );
   _civicrm_entity_link_addformatters('civicrm_tag',$link_fields,$fields);
  $option_fields = array(
  );
  //_civicrm_entity_option_addformatters('civicrm_tag',$option_fields,$fields);
  $yes_no_fields = array(
    'is_reserved',
    'is_tagset',
    'is_selectable',
  );
  _civicrm_entity_yesno_addformatters('civicrm_tag',$yes_no_fields,$fields);
}

function _civicrm_entity_yesno_addformatters($entity_type,$yes_no_fields,&$fields){
  foreach($yes_no_fields as $name) {
     $fields[$entity_type][$name]['properties']['formatters'] = array (
        'default' => 'Raw Value',
        'civicrm_yes_no' => 'Yes/No',
        'civicrm_true_false' => 'True/False',
     );
  }
}

function _civicrm_entity_option_addformatters($entity_type,$option_fields,&$fields){
  foreach($option_fields as $name) {
     $fields[$entity_type][$name]['properties']['formatters'] = array (
        'default' => 'Option ID',
        'civicrm_option_value' => 'Option Value',
     );
  }
}

function _civicrm_entity_link_addformatters($entity_type,$link_fields,&$fields){
  foreach($link_fields as $link_field) {
     $fields[$entity_type][$link_field['link_field']]['properties']['formatters'] = array (
       'default' => 'Default',
       'civicrm_link' => 'Link',
     );
     $fields[$entity_type][$link_field['link_field']]['properties']['link_entity'] = $link_field['target'];
  }
}

/**
 * Default Display Suite Render handler for CiviCRM "fields".
 */
function _civicrm_entity_render_fields($field) {
  $settings = isset($field['formatter_settings']) ? $field['formatter_settings'] : array();
  $settings += $field['properties']['default'];

  $wrapper = entity_metadata_wrapper($field['entity_type'], $field['entity']->id);


  //civicrm_contact civi_user field needs special handling
  switch($field['entity_type']) {
    case 'civicrm_contact':
      $formatted_value = _civicrm_entity_contact_get_formatted_values($field,$wrapper);
      break;
    case 'civicrm_participant':
      $formatted_value = _civicrm_entity_participant_get_formatted_values($field,$wrapper,$field['entity']);
      break;
    default: $formatted_value = $wrapper->{$field['field_name']}->value();
    break;
  }

   // primary_contact_id_contact and other fields are objects produced by the meta wrapper
   // Will be ease to generate links to the entities if it is consistent across entities
   if(is_object($formatted_value)){
    $formatted_value = $wrapper->{$field['field_name']}->id->value();
   }
   if($field['formatter'] == 'civicrm_link') {
      global $base_url;
      if($formatted_value){
        $formatted_value = '<a href="'. $base_url . '/'. str_replace('_','-',$field['properties']['link_entity']) . '/' . $formatted_value . '">'. _civicrm_entity_get_entity_label($field['properties']['link_entity'],$formatted_value) . '</a>';
      }
   }

   if($field['formatter'] == 'civicrm_yes_no') {
     if($formatted_value) {
       $formatted_value = 'Yes';
     }
     else {
       $formatted_value = 'No';
     }
   }
   if($field['formatter'] == 'civicrm_true_false') {
     if($formatted_value) {
       $formatted_value = 'True';
     }
     else {
       $formatted_value = 'False';
     }
   }

   if($field['formatter'] == 'civicrm_option_value') {
     if($formatted_value){
       $formatted_value = _civicrm_entity_option_lookup($field,explode(',', $formatted_value));
     }
   }

  // Wrapper and class.
  if (!empty($settings['wrapper'])) {
    $wrapper = check_plain($settings['wrapper']);
    $class = (!empty($settings['class'])) ? ' class="' . check_plain($settings['class']) . '"' : '';
    $output = '<' . $wrapper . $class . '>' . $formatted_value . '</' . $wrapper . '>';
  }

  return $output;
}

function _civicrm_entity_get_entity_label($entity_type,$id) {
  $wrapper = entity_metadata_wrapper($entity_type,$id);
  return $wrapper->label();
}

/*
 * Returns a comma delimited list of option labels from id values
 *
 */
function _civicrm_entity_option_lookup($field,$values){
  $result = civicrm_api3(substr($field['entity_type'],8), 'getoptions', array(
          'field' => $field['field_name'],
  ));
  $fm = array();
  foreach($values as $value) {
    $fm[] = $result['values'][$value];
  }
  return implode(",",$fm);
}

/*
 * Contact entity field formatted value special handling
 *
 */
function _civicrm_entity_contact_get_formatted_values(&$field,$wrapper){
  switch($field['field_name']){
    case 'contact_sub_type':
    case 'preferred_communication_method':
       return _civicrm_entity_formatted_output_of_arrays($field,$wrapper);
    default: return $wrapper->{$field['field_name']}->value();
  }
}


function _civicrm_entity_participant_get_formatted_values(&$field,$wrapper,$entity){
  switch($field['field_name']) {
    case 'role_id':
    case 'status_id':
    case 'registered_date':
    case 'source':
    case 'fee_currency':
    case 'is_pay_later':
    case 'registered_by_id':
    case 'is_test':
       return $entity->{'participant_'.$field['field_name']};
    case 'fee_level':
       return $entity->{'participant_'.$field['field_name']}[0];
    default: return $wrapper->{$field['field_name']}->value();
  }
}

/*
 * Returns a comma delimited list of field values which are arrays
 *
 */
function _civicrm_entity_formatted_output_of_arrays(&$field,$wrapper) {
  $values = $wrapper->{$field['field_name']}->value();
  if(is_array($values)) {
    return  implode(",",$values );
  }
  else {
    return '';
  }
}

