<?php

/**
 *
 * @return multitype:multitype:string boolean NULL
 */

function civicrm_entity_actions_action_info() {

  return array(
    'civicrm_entity_actions_activity_assign_action' => array(
      'label' => t('Assign Activity'),
      'type' => 'civicrm_activity',
      'configurable' => TRUE,
    ),
    'civicrm_entity_actions_activity_unassign_action' => array(
      'label' => t('Unassign Activity'),
      'type' => 'civicrm_activity',
    ),
    'civicrm_entity_actions_contact_add_to_group_action' => array(
      'label' => t('Add Contact to Group'),
      'type' => 'civicrm_contact',
      'configurable' => TRUE,
    ),
    'civicrm_entity_actions_contact_remove_from_group_action' => array(
      'label' => t('Remove Contact From Group'),
      'type' => 'civicrm_contact',
      'configurable' => TRUE,
    ),
    'civicrm_entity_actions_contact_add_entity_tag_action' => array(
      'label' => t('Tag Contact'),
      'type' => 'civicrm_contact',
      'configurable' => TRUE,
    ),
  );
}

/**
 *
 * @param unknown $object
 * @param array $context
 */

function civicrm_entity_actions_activity_assign_action(&$object, $context = array()) {
  civicrm_api3('activity', 'create', array(
    'id' => $object->id,
    'assignee_contact_id' => $context['state']['entity_id'])
  );
}

/**
 *
 * @param array $context
 * @return multitype:string unknown
 */

function civicrm_entity_actions_activity_assign_action_form( $context = array()) {
  $entities = _civicrm_entity_enabled_entities();
  $entity = $entities[$context['entity_type']];
  $form[$entity]['assignee_contact_id'] = array(
      '#type' => 'entityreference',
      '#title' => t('Assign To'),
      '#era_entity_type' => 'civicrm_contact',
  );
  return $form;
}

/**
 *
 * @param unknown $form
 * @param unknown $form_state
 * @return multitype:NULL
 */

function civicrm_entity_actions_activity_assign_action_submit($form, $form_state) {
  return array('state' => $form_state['values']['assignee_contact_id']);
}

/**
 *
 * @param unknown $object
 * @param array $context
 */

function civicrm_entity_actions_activity_unassign_action(&$object, $context = array()) {
  if(!civicrm_initialize()) {
    return;
  }
  civicrm_api3('activity', 'create', array(
    'id' => $object->id,
    'deleteActivityAssignment' => TRUE)
  );
}

/**
 *
 * @param unknown $object
 * @param array $context
 */

function civicrm_entity_actions_contact_add_to_group_action(&$object, $context = array()) {
  civicrm_api3('group_contact', 'create', array(
      'contact_id' => $object->id,
      'group_id' => $context['state']['entity_id'],
      'status' => 'Added',
    )
  );
}

/**
 *
 * @param array $context
 * @return multitype:string unknown
 */

function civicrm_entity_actions_contact_add_to_group_action_form( $context = array()) {
  $form['civicrm_contact']['group_id'] = array(
    '#type' => 'entityreference',
    '#title' => t('Add To Group'),
    '#era_entity_type' => 'civicrm_group',
  );
  return $form;
}

/**
 *
 * @param array $context
 * @return multitype:string unknown
 */

function civicrm_entity_actions_contact_add_to_group_action_submit($form, $form_state) {
  return array('state' => $form_state['values']['group_id']);
}

/**
 *
 * @param unknown $object
 * @param array $context
 */

function civicrm_entity_actions_contact_remove_from_group_action(&$object, $context = array()) {
  civicrm_api3('group_contact', 'create', array(
  'contact_id' => $object->id,
  'group_id' => $context['state']['entity_id'],
  'status' => 'Removed',
  )
  );
}

/**
 *
 * @param array $context
 * @return multitype:string unknown
 */

function civicrm_entity_actions_contact_remove_from_group_action_form( $context = array()) {
  $form['civicrm_contact']['group_id'] = array(
      '#type' => 'entityreference',
      '#title' => t('Remove From'),
      '#era_entity_type' => 'civicrm_group',
  );
  return $form;
}

/**
 *
 * @param array $context
 * @return multitype:string unknown
 */

function civicrm_entity_actions_contact_remove_from_group_action_submit($form, $form_state) {
  return array('state' => $form_state['values']['group_id']);
}

/**
 *
 * @param unknown $object
 * @param array $context
 */

function civicrm_entity_actions_contact_add_entity_tag_action(&$object, $context = array()) {
  civicrm_api3('entity_tag', 'create', array(
    'contact_id' => $object->id,
    'tag_id' => $context['state']['entity_id'],
  )
  );
}

/**
 *
 * @param array $context
 * @return multitype:string unknown
 */

function civicrm_entity_actions_contact_add_entity_tag_action_form( $context = array()) {
  $form['civicrm_contact']['tag_id'] = array(
      '#type' => 'entityreference',
      '#title' => t('Add Tag'),
      '#era_entity_type' => 'civicrm_tag',
  );
  return $form;
}

/**
 *
 * @param array $context
 * @return multitype:string unknown
 */

function civicrm_entity_actions_contact_add_entity_tag_action_submit($form, $form_state) {
  return array('state' => $form_state['values']['tag_id']);
}
