<?php

/**
 * Implements hook_entity_info_alter().
 *
 * @param $entity_info
 */
function civicrm_entity_inline_entity_info_alter(&$entity_info) {
  $entities = _civicrm_entity_enabled_entities();

  foreach ($entities as $drupal => $civi) {
    $entity_info[$drupal]['inline entity form'] = array(
      'controller' => 'CivicrmInlineEntityFormController',
    );
  }
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 *
 * @param $entity_form
 * @param $form_state
 */
function civicrm_entity_inline_inline_entity_form_entity_form_alter(&$entity_form, &$form_state) {
  $form_id = $form_state['build_info']['form_id'] . '_ief_' . $entity_form['#entity_type'] . '_' . $entity_form['#bundle'];
  $entity_form['#form_id'] = $form_id;

  //drupal_alter(array('form', 'form_' . $form_id, 'form_' . $form_state['build_info']['base_form_id']), $entity_form, $form_state, $form_id);
  drupal_alter('form', $entity_form, $form_state, $form_id);
}
