# Schema for the civicrm_entity filter plugins.

views.filter.civicrm_entity_civicrm_activity_contact_record_filter:
  type: views_filter
  label: 'Numeric'
  mapping:
    expose:
      type: mapping
      label: 'Exposed'
      mapping:
        min_placeholder:
          type: label
          label: 'Min placeholder'
        max_placeholder:
          type: label
          label: 'Max placeholder'
        placeholder:
          type: label
          label: 'Placeholder'

views.filter_value.civicrm_entity_civicrm_activity_contact_record_filter:
  type: mapping
  label: 'Numeric'
  mapping:
    min:
      type: string
      label: 'Min'
    max:
      type: string
      label: 'And max'
    value:
      type: string
      label: 'Value'
